### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Ragzouken** [IRL2/nanover-imd-vr-2024#50]
Remove SteamVR references, point to release, instructions for running etc

**Comment by rhoslynroebuck** [comment]
Also would be good to mention that you might need to run the following commands to update the submodule:
```
git submodule sync
git submodule update --init --recursive --remote
```

**Comment by Ragzouken** [comment]
Closed by https://github.com/IRL2/nanover-imd/commit/47fa78874f073b79ae736979ca3dc5a85e5a13d4
