### ISSUE TITLE
Forces shouldn't be applied to solvent molecules when solvent is hidden

### ISSUE THREAD

**Issue by phuddha** [IRL2/nanover-imd-vr-2024#52]
When using explicit solvent (e.g. water) and hiding the solvent molecules the user forces are still applied to the nearest atom even though the nearest atom may be a solvent molecule and is invisible. The forces should only be applied to visible atoms.

**Comment by Ragzouken** [comment]
Fixed in https://github.com/IRL2/nanover-imd/pull/61
